[package]
name = "trg"
version = "0.1.0"
edition = "2021"

[dependencies]
annotate-snippets = "0.11.5"
bon = "3.3.2"
num-traits = "0.2.19"
winnow = "0.7.3"

[dev-dependencies]
anyhow = "1.0.100"
rand = "0.9.2"
rand_distr = "0.5.1"
serde_json = "1.0.145"
uom = "0.37.0"
